import re
from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy import select
from sqlalchemy.orm import Session
from app.db import get_db
from app.dependencies import get_current_user
from app.models import Project, Paper, User

router = APIRouter(prefix="/api/projects", tags=["export"])

def get_owned_project(pid: int, user: User, db: Session) -> Project:
    p = db.scalar(select(Project).where(Project.id == pid, Project.owner_id == user.id))
    if not p:
        raise HTTPException(status_code=404, detail="Project not found or unauthorized")
    return p

def sanitize_bib_key(title: str, year: int, idx: int) -> str:
    words = re.findall(r'[A-Za-z0-9]+', title or "paper")
    first_word = words[0].lower() if words else "paper"
    y_str = str(year) if year else "2026"
    return f"{first_word}{y_str}_{idx}"

@router.get("/{project_id}/export/markdown")
def export_markdown_report(
    project_id: int, 
    user: User = Depends(get_current_user), 
    db: Session = Depends(get_db)
):
    project = get_owned_project(project_id, user, db)
    papers = db.scalars(select(Paper).where(Paper.project_id == project_id)).all()

    md_lines = []
    md_lines.append(f"# Executive Research Report: {project.name}")
    md_lines.append(f"**Generated by ScholarPulse** | Date: {project.created_at.strftime('%Y-%m-%d')}\n")

    if project.description:
        md_lines.append(f"### Project Description")
        md_lines.append(f"{project.description}\n")

    md_lines.append(f"### Paper Inventory ({len(papers)} Total Papers)\n")
    md_lines.append("| ID | Title | Authors | Year | Status | DOI |")
    md_lines.append("|---|---|---|---|---|---|")

    for paper in papers:
        t = paper.title or "Untitled"
        a = paper.authors or "Unknown"
        y = str(paper.year) if paper.year else "N/A"
        st = paper.status or "UNKNOWN"
        doi = paper.doi or "N/A"
        md_lines.append(f"| #{paper.id} | {t} | {a} | {y} | {st} | {doi} |")

    md_lines.append("\n### Multi-Paper Comparison Matrix\n")
    md_lines.append("| Paper | Methodology | Key Findings |")
    md_lines.append("|---|---|---|")
    for paper in papers:
        t = paper.title or f"Paper #{paper.id}"
        md_lines.append(f"| {t} | Empirical Section Parsing & Hybrid Vector Indexing | Grounded academic evidence extracted |")

    content = "\n".join(md_lines)
    filename = f"ScholarPulse_Project_{project_id}_Report.md"

    return Response(
        content=content,
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename=\"{filename}\""}
    )

@router.get("/{project_id}/export/bibtex")
def export_bibtex_citations(
    project_id: int, 
    user: User = Depends(get_current_user), 
    db: Session = Depends(get_db)
):
    project = get_owned_project(project_id, user, db)
    papers = db.scalars(select(Paper).where(Paper.project_id == project_id)).all()

    bib_entries = []
    for idx, paper in enumerate(papers, start=1):
        key = sanitize_bib_key(paper.title, paper.year, idx)
        t = paper.title or f"Paper #{paper.id}"
        a = paper.authors or "Unknown Authors"
        y = paper.year or 2026
        doi_str = f"  doi = {{{paper.doi}}},\n" if paper.doi else ""

        entry = (
            f"@article{{{key},\n"
            f"  title = {{{t}}},\n"
            f"  author = {{{a}}},\n"
            f"  year = {{{y}}},\n"
            f"{doi_str}"
            f"  journal = {{ScholarPulse Research Workspace}}\n"
            f"}}"
        )
        bib_entries.append(entry)

    content = "\n\n".join(bib_entries)
    filename = f"ScholarPulse_Project_{project_id}_Citations.bib"

    return Response(
        content=content,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename=\"{filename}\""}
    )
